#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLinq
{
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Data;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Linq;
    using System.Linq.Expressions;
    using System.ComponentModel;
    using System;
    using System.Configuration;

    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "ghyusers")]
    public partial class UserDataContext : System.Data.Linq.DataContext
    {

        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

        #region 可扩展性方法定义
        partial void OnCreated();
        partial void Insertuser(user instance);
        partial void Updateuser(user instance);
        partial void Deleteuser(user instance);
        partial void Insertrole(role instance);
        partial void Updaterole(role instance);
        partial void Deleterole(role instance);
        #endregion

        public UserDataContext() : 
				base(global::DataLinq.Properties.Settings.Default.ghyusersConnectionString, mappingSource)
		{
			OnCreated();
		}
        /*public UserDataContext() :
            base(ConfigurationManager.ConnectionStrings["conGhyusers"].ConnectionString, mappingSource)
        {
            OnCreated();
        }*/

        public UserDataContext(string connection) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public UserDataContext(System.Data.IDbConnection connection) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public UserDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public UserDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public System.Data.Linq.Table<user> user
        {
            get
            {
                return this.GetTable<user>();
            }
        }

        public System.Data.Linq.Table<role> role
        {
            get
            {
                return this.GetTable<role>();
            }
        }

        public System.Data.Linq.Table<user_role> user_role
        {
            get
            {
                return this.GetTable<user_role>();
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.[user]")]
    public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private System.Guid _uID;

        private string _uNum;

        private string _uName;

        private string _uPwd;

        private string _uMail;

        private string _uGrade;

        private System.Nullable<int> _uSex;

        private string _uTel;

        private string _uPic;

        private string _uIP;

        private System.DateTime _registerTime;

        private string _trueName;

        private int _state;

        private System.DateTime _lastLogin;

        #region 可扩展性方法定义
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnuIDChanging(System.Guid value);
        partial void OnuIDChanged();
        partial void OnuNumChanging(string value);
        partial void OnuNumChanged();
        partial void OnuNameChanging(string value);
        partial void OnuNameChanged();
        partial void OnuPwdChanging(string value);
        partial void OnuPwdChanged();
        partial void OnuMailChanging(string value);
        partial void OnuMailChanged();
        partial void OnuGradeChanging(string value);
        partial void OnuGradeChanged();
        partial void OnuSexChanging(System.Nullable<int> value);
        partial void OnuSexChanged();
        partial void OnuTelChanging(string value);
        partial void OnuTelChanged();
        partial void OnuPicChanging(string value);
        partial void OnuPicChanged();
        partial void OnuIPChanging(string value);
        partial void OnuIPChanged();
        partial void OnregisterTimeChanging(System.DateTime value);
        partial void OnregisterTimeChanged();
        partial void OntrueNameChanging(string value);
        partial void OntrueNameChanged();
        partial void OnstateChanging(int value);
        partial void OnstateChanged();
        partial void OnlastLoginChanging(System.DateTime value);
        partial void OnlastLoginChanged();
        #endregion

        public user()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_uID", DbType = "UniqueIdentifier NOT NULL", IsPrimaryKey = true)]
        public System.Guid uID
        {
            get
            {
                return this._uID;
            }
            set
            {
                if ((this._uID != value))
                {
                    this.OnuIDChanging(value);
                    this.SendPropertyChanging();
                    this._uID = value;
                    this.SendPropertyChanged("uID");
                    this.OnuIDChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_uNum", DbType = "NVarChar(20) NOT NULL", CanBeNull = false)]
        public string uNum
        {
            get
            {
                return this._uNum;
            }
            set
            {
                if ((this._uNum != value))
                {
                    this.OnuNumChanging(value);
                    this.SendPropertyChanging();
                    this._uNum = value;
                    this.SendPropertyChanged("uNum");
                    this.OnuNumChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_uName", DbType = "NVarChar(20) NOT NULL", CanBeNull = false)]
        public string uName
        {
            get
            {
                return this._uName;
            }
            set
            {
                if ((this._uName != value))
                {
                    this.OnuNameChanging(value);
                    this.SendPropertyChanging();
                    this._uName = value;
                    this.SendPropertyChanged("uName");
                    this.OnuNameChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_uPwd", DbType = "NVarChar(50) NOT NULL", CanBeNull = false)]
        public string uPwd
        {
            get
            {
                return this._uPwd;
            }
            set
            {
                if ((this._uPwd != value))
                {
                    this.OnuPwdChanging(value);
                    this.SendPropertyChanging();
                    this._uPwd = value;
                    this.SendPropertyChanged("uPwd");
                    this.OnuPwdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_uMail", DbType = "NVarChar(50)")]
        public string uMail
        {
            get
            {
                return this._uMail;
            }
            set
            {
                if ((this._uMail != value))
                {
                    this.OnuMailChanging(value);
                    this.SendPropertyChanging();
                    this._uMail = value;
                    this.SendPropertyChanged("uMail");
                    this.OnuMailChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_uGrade", DbType = "NVarChar(4)")]
        public string uGrade
        {
            get
            {
                return this._uGrade;
            }
            set
            {
                if ((this._uGrade != value))
                {
                    this.OnuGradeChanging(value);
                    this.SendPropertyChanging();
                    this._uGrade = value;
                    this.SendPropertyChanged("uGrade");
                    this.OnuGradeChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_uSex", DbType = "Int")]
        public System.Nullable<int> uSex
        {
            get
            {
                return this._uSex;
            }
            set
            {
                if ((this._uSex != value))
                {
                    this.OnuSexChanging(value);
                    this.SendPropertyChanging();
                    this._uSex = value;
                    this.SendPropertyChanged("uSex");
                    this.OnuSexChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_uTel", DbType = "NVarChar(50)")]
        public string uTel
        {
            get
            {
                return this._uTel;
            }
            set
            {
                if ((this._uTel != value))
                {
                    this.OnuTelChanging(value);
                    this.SendPropertyChanging();
                    this._uTel = value;
                    this.SendPropertyChanged("uTel");
                    this.OnuTelChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_uPic", DbType = "NVarChar(500)")]
        public string uPic
        {
            get
            {
                return this._uPic;
            }
            set
            {
                if ((this._uPic != value))
                {
                    this.OnuPicChanging(value);
                    this.SendPropertyChanging();
                    this._uPic = value;
                    this.SendPropertyChanged("uPic");
                    this.OnuPicChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_uIP", DbType = "NVarChar(50)")]
        public string uIP
        {
            get
            {
                return this._uIP;
            }
            set
            {
                if ((this._uIP != value))
                {
                    this.OnuIPChanging(value);
                    this.SendPropertyChanging();
                    this._uIP = value;
                    this.SendPropertyChanged("uIP");
                    this.OnuIPChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_registerTime", DbType = "DateTime NOT NULL")]
        public System.DateTime registerTime
        {
            get
            {
                return this._registerTime;
            }
            set
            {
                if ((this._registerTime != value))
                {
                    this.OnregisterTimeChanging(value);
                    this.SendPropertyChanging();
                    this._registerTime = value;
                    this.SendPropertyChanged("registerTime");
                    this.OnregisterTimeChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_trueName", DbType = "NVarChar(20)")]
        public string trueName
        {
            get
            {
                return this._trueName;
            }
            set
            {
                if ((this._trueName != value))
                {
                    this.OntrueNameChanging(value);
                    this.SendPropertyChanging();
                    this._trueName = value;
                    this.SendPropertyChanged("trueName");
                    this.OntrueNameChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_state", DbType = "Int NOT NULL")]
        public int state
        {
            get
            {
                return this._state;
            }
            set
            {
                if ((this._state != value))
                {
                    this.OnstateChanging(value);
                    this.SendPropertyChanging();
                    this._state = value;
                    this.SendPropertyChanged("state");
                    this.OnstateChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_lastLogin", DbType = "DateTime NOT NULL")]
        public System.DateTime lastLogin
        {
            get
            {
                return this._lastLogin;
            }
            set
            {
                if ((this._lastLogin != value))
                {
                    this.OnlastLoginChanging(value);
                    this.SendPropertyChanging();
                    this._lastLogin = value;
                    this.SendPropertyChanged("lastLogin");
                    this.OnlastLoginChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.role")]
    public partial class role : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private System.Guid _roleID;

        private string _roleName;

        #region 可扩展性方法定义
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnroleIDChanging(System.Guid value);
        partial void OnroleIDChanged();
        partial void OnroleNameChanging(string value);
        partial void OnroleNameChanged();
        #endregion

        public role()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_roleID", DbType = "UniqueIdentifier NOT NULL", IsPrimaryKey = true)]
        public System.Guid roleID
        {
            get
            {
                return this._roleID;
            }
            set
            {
                if ((this._roleID != value))
                {
                    this.OnroleIDChanging(value);
                    this.SendPropertyChanging();
                    this._roleID = value;
                    this.SendPropertyChanged("roleID");
                    this.OnroleIDChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_roleName", DbType = "NVarChar(20) NOT NULL", CanBeNull = false)]
        public string roleName
        {
            get
            {
                return this._roleName;
            }
            set
            {
                if ((this._roleName != value))
                {
                    this.OnroleNameChanging(value);
                    this.SendPropertyChanging();
                    this._roleName = value;
                    this.SendPropertyChanged("roleName");
                    this.OnroleNameChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.[user-role]")]
    public partial class user_role
    {

        private System.Guid _uID;

        private System.Guid _roleID;

        private int _state;

        public user_role()
        {
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_uID", DbType = "UniqueIdentifier NOT NULL")]
        public System.Guid uID
        {
            get
            {
                return this._uID;
            }
            set
            {
                if ((this._uID != value))
                {
                    this._uID = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_roleID", DbType = "UniqueIdentifier NOT NULL")]
        public System.Guid roleID
        {
            get
            {
                return this._roleID;
            }
            set
            {
                if ((this._roleID != value))
                {
                    this._roleID = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_state", DbType = "Int NOT NULL")]
        public int state
        {
            get
            {
                return this._state;
            }
            set
            {
                if ((this._state != value))
                {
                    this._state = value;
                }
            }
        }
    }
}
#pragma warning restore 1591
